### ISSUE TITLE
1.18.2?

### ISSUE THREAD

**Issue by PaladinFallen** [crashtheparty/CrashAPI#4]
[22:56:14] [Server thread/INFO]: [CrashAPI] Loading CrashAPI v1.1.1
[22:56:14] [Server thread/INFO]: [CrashAPI] Checking Bukkit Version: 1.18.2
[22:56:14] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
[22:56:14] [Server thread/WARN]: 	at CrashAPI.jar//org.ctp.crashapi.version.BukkitVersion.allowedBukkitVersion(BukkitVersion.java:92)
[22:56:14] [Server thread/WARN]: 	at CrashAPI.jar//org.ctp.crashapi.version.BukkitVersion.<init>(BukkitVersion.java:28)
[22:56:14] [Server thread/WARN]: 	at CrashAPI.jar//org.ctp.crashapi.CrashAPI.onLoad(CrashAPI.java:33)
[22:56:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:423)
[22:56:14] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:288)
[22:56:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1165)
[22:56:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[22:56:14] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[22:56:14] [Server thread/WARN]: [CrashAPI] Could not find version 1.18.2.
[22:56:14] [Server thread/INFO]: [CrashAPI] Checking Bukkit API Version: v1_18_R2
[22:56:14] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
[22:56:14] [Server thread/WARN]: 	at CrashAPI.jar//org.ctp.crashapi.version.BukkitVersion.allowedBukkitVersion(BukkitVersion.java:109)
[22:56:14] [Server thread/WARN]: 	at CrashAPI.jar//org.ctp.crashapi.version.BukkitVersion.<init>(BukkitVersion.java:28)
[22:56:14] [Server thread/WARN]: 	at CrashAPI.jar//org.ctp.crashapi.CrashAPI.onLoad(CrashAPI.java:33)
[22:56:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:423)
[22:56:14] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:288)
[22:56:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1165)
[22:56:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[22:56:14] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[22:56:14] [Server thread/ERROR]: [CrashAPI] This version is not defined! Features that require NMS have been disabled, and issues may arise with certain features. Please wait for an update for this version.
[22:56:15] [Server thread/INFO]: [CrashAPI] Initializing main configuration...
[22:56:15] [Server thread/INFO]: [CrashAPI] Main configuration initialized!
[22:56:15] [Server thread/INFO]: [CrashAPI] Initializing language configuration...
[22:56:15] [Server thread/INFO]: [CrashAPI] Language configuration initialized!

**Comment by proy27** [comment]
+1
